export default function Litepaper() {
  return (
    <main className="min-h-screen bg-black text-white select-none">

      {/* NAVBAR */}
      <nav className="w-full px-8 py-6 flex justify-between items-center border-b border-white/10">

        {/* CHAINED LOGO */}
        <a
          href="/"
          className="flex items-center"
        >
          <img
            src="/chained-header.png"
            alt="chained"
            draggable={false}
            className="h-10 md:h-12 w-auto object-contain select-none"
          />
        </a>

        {/* HOME */}
        <a
          href="/"
          className="text-sm text-gray-500 hover:text-white transition"
        >
          HOME
        </a>

      </nav>


      {/* HEADER */}
      <section className="max-w-4xl mx-auto px-6 pt-24 pb-16">

        {/* LITEPAPER TITLE */}
        <h1 className="text-5xl md:text-7xl font-bold tracking-tight">
          Litepaper
        </h1>

        {/* SLOGAN */}
        <p className="mt-6 text-lg md:text-xl text-gray-400 max-w-2xl leading-relaxed">
          Don&apos;t launch alone.
          <br />
          Build on a network.
        </p>

      </section>


      {/* LITEPAPER CONTENT */}
      <section className="max-w-4xl mx-auto px-6 pb-32">


        {/* 01 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            01
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            What Is CHAINED?
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              CHAINED is a networked token launch and economic
              infrastructure designed to connect tokens through
              hierarchical relationships.
            </p>

            <p>
              Instead of treating every token as a completely isolated
              project, CHAINED creates a structure in which new tokens
              can become economically connected to existing tokens.
            </p>

            <p>
              The purpose is to build an ecosystem where the activity
              generated by one token can contribute to the wider network
              rather than remaining completely isolated.
            </p>

            <p className="text-white font-medium">
              The network starts with one token: CHAIN.
            </p>

          </div>

        </article>


        {/* 02 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            02
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            The First Link: CHAIN
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              CHAIN is the first token of the CHAINED network and
              represents the root of the system.
            </p>

            <p>
              CHAIN is already live. The CHAINED launchpad, however,
              is still under development and is not yet open for public
              token creation.
            </p>

            <p>
              The first generation of connected tokens will be created
              through a controlled selection process. This initial stage
              is intended to establish the first branches of the network
              and test the system before broader creator access is opened.
            </p>

          </div>

        </article>


        {/* 03 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            03
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            The Chain
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              CHAINED is structured as a maximum five-level chain.
              Each token after CHAIN can become connected to a parent
              token above it.
            </p>

            <div className="my-10 py-10 border border-white/10 text-center">

              <p className="text-xl md:text-2xl text-white tracking-wide">
                CHAIN
              </p>

              <p className="text-gray-600 my-3">
                ↓
              </p>

              <p className="text-xl md:text-2xl text-white tracking-wide">
                LINK 2
              </p>

              <p className="text-gray-600 my-3">
                ↓
              </p>

              <p className="text-xl md:text-2xl text-white tracking-wide">
                LINK 3
              </p>

              <p className="text-gray-600 my-3">
                ↓
              </p>

              <p className="text-xl md:text-2xl text-white tracking-wide">
                LINK 4
              </p>

              <p className="text-gray-600 my-3">
                ↓
              </p>

              <p className="text-xl md:text-2xl text-white tracking-wide">
                LINK 5
              </p>

            </div>

            <p>
              The structure is not intended to create a single straight
              line of projects. Each eligible token can potentially
              become a parent for another token, allowing the network
              to branch into multiple connected ecosystems.
            </p>

            <p>
              The fifth link represents the maximum depth of the
              initial CHAINED architecture.
            </p>

          </div>

        </article>


        {/* 04 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            04
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            Creator Selection
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              The first connected tokens following CHAIN will not be
              created through unrestricted public access.
            </p>

            <p>
              Creator applications will be opened for the second link.
              Applicants will be evaluated through an initial selection
              process designed to determine which projects become the
              first connected tokens in the network.
            </p>

            <p>
              This initial selection phase is intended to establish the
              foundation of the ecosystem before the launchpad becomes
              broadly accessible.
            </p>

            <p className="text-white font-medium">
              After the second link is established, future creators will
              be able to create tokens by connecting them to eligible
              parent tokens without requiring a new selection process
              for every launch.
            </p>

          </div>

        </article>


        {/* 05 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            05
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            Parent–Child Connection
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              Every token created inside the CHAINED network, except
              the root token, is connected to a parent token.
            </p>

            <p>
              This connection is economic as well as structural.
              A child token is not intended to operate as a completely
              independent asset disconnected from its parent.
            </p>

            <p>
              When a child token is purchased, a defined portion of the
              required transaction value must also be allocated toward
              the corresponding parent token.
            </p>

            <p>
              The protocol is also designed so that a child position
              cannot be exited independently from its required parent
              position. The parent position must be unwound before the
              corresponding child position can be fully exited.
            </p>

            <p>
              The exact implementation of these mechanics will be
              defined during protocol development and security testing.
            </p>

          </div>

        </article>


        {/* 06 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            06
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            Fee Flow
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              The economic relationship between tokens extends beyond
              the initial purchase.
            </p>

            <p>
              A defined portion of trading fees generated by a child
              token can flow upward through its parent chain.
            </p>

            <div className="my-10 py-10 border border-white/10 text-center">

              <p className="text-xl md:text-2xl text-white tracking-wide">
                LINK 5
              </p>

              <p className="text-gray-600 my-3">
                ↓
              </p>

              <p className="text-xl md:text-2xl text-white tracking-wide">
                LINK 4
              </p>

              <p className="text-gray-600 my-3">
                ↓
              </p>

              <p className="text-xl md:text-2xl text-white tracking-wide">
                LINK 3
              </p>

              <p className="text-gray-600 my-3">
                ↓
              </p>

              <p className="text-xl md:text-2xl text-white tracking-wide">
                LINK 2
              </p>

              <p className="text-gray-600 my-3">
                ↓
              </p>

              <p className="text-xl md:text-2xl text-white tracking-wide">
                CHAIN
              </p>

            </div>

            <p>
              The share received by each successive level is designed
              to decrease as the distance from the transaction increases.
            </p>

            <p>
              As a result, the direct parent receives the strongest
              economic relationship, while higher-level ancestors can
              continue to participate with progressively smaller shares.
            </p>

            <p>
              Exact fee percentages will be determined during economic
              testing and protocol development.
            </p>

          </div>

        </article>


        {/* 07 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            07
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            Why Multiple Links?
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              A system in which every creator connects directly to the
              first token would naturally concentrate activity around
              a single asset.
            </p>

            <p>
              CHAINED is designed to create an alternative incentive.
              A creator may find it more economically attractive to build
              on a recently established and successful token rather than
              always connecting directly to CHAIN.
            </p>

            <p>
              This creates an incentive for the network to develop new
              branches rather than repeatedly producing isolated tokens
              around the same root asset.
            </p>

            <p>
              Over time, the network can therefore develop into a
              branching structure of projects connected through economic
              relationships.
            </p>

          </div>

        </article>


        {/* 08 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            08
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            One Name, One Token
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              Each token name can only be used once within the CHAINED
              launchpad.
            </p>

            <p>
              This creates a unique identity for every project launched
              through the network and prevents multiple tokens with the
              same name from competing inside the same launchpad.
            </p>

            <p>
              This rule applies to the CHAINED launchpad itself and does
              not prevent unrelated platforms or individuals from using
              similar names elsewhere.
            </p>

          </div>

        </article>


        {/* 09 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            09
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            The Purpose
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              Traditional token launches are often isolated events.
              A token can succeed or fail without creating a meaningful
              economic relationship with other projects.
            </p>

            <p>
              CHAINED is designed to create an ecosystem in which
              projects are connected through their economic structure.
            </p>

            <p>
              The objective is not to guarantee that every token will
              succeed, nor to make malicious behavior or token failure
              impossible.
            </p>

            <p>
              Instead, CHAINED aims to reduce the dependence of the
              ecosystem on isolated launches by creating relationships
              between projects and distributing a portion of economic
              activity throughout the network.
            </p>

            <p className="text-white font-medium">
              The goal is an ecosystem where creators can benefit from
              the network they help build.
            </p>

          </div>

        </article>


        {/* 10 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            10
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            Protocol Development
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              CHAINED is currently in its early development stage.
              CHAIN, the first token of the network, is live while the
              connected launchpad infrastructure remains under
              development.
            </p>

            <p>
              Development will focus on implementing and testing the
              core components required for the network.
            </p>

            <div className="my-8 space-y-4">

              <div className="border border-white/10 px-5 py-4">
                <p className="text-white font-medium">
                  Parent–Child Infrastructure
                </p>
                <p className="text-gray-500 text-sm mt-1">
                  Establish and enforce the economic relationship between
                  connected tokens.
                </p>
              </div>

              <div className="border border-white/10 px-5 py-4">
                <p className="text-white font-medium">
                  Fee Routing
                </p>
                <p className="text-gray-500 text-sm mt-1">
                  Route defined portions of trading activity through the
                  parent chain.
                </p>
              </div>

              <div className="border border-white/10 px-5 py-4">
                <p className="text-white font-medium">
                  Creator System
                </p>
                <p className="text-gray-500 text-sm mt-1">
                  Enable applications, token creation and parent
                  selection.
                </p>
              </div>

              <div className="border border-white/10 px-5 py-4">
                <p className="text-white font-medium">
                  Token Registry
                </p>
                <p className="text-gray-500 text-sm mt-1">
                  Maintain unique token identities within the launchpad.
                </p>
              </div>

            </div>

            <p>
              Technical architecture, economic parameters, security
              mechanisms and implementation details will be refined
              through research, prototyping, testing and auditing.
            </p>

          </div>

        </article>


        {/* 11 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            11
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            Roadmap
          </h2>

          <div className="space-y-8 text-gray-400 leading-8">

            <div>
              <p className="text-white font-medium">
                Phase 0 — Genesis
              </p>

              <p className="mt-1">
                Launch CHAIN as the first token and establish the root
                of the network.
              </p>
            </div>

            <div>
              <p className="text-white font-medium">
                Phase 1 — Launchpad Development
              </p>

              <p className="mt-1">
                Develop the core infrastructure for token creation,
                parent–child relationships, fee routing and token
                registration.
              </p>
            </div>

            <div>
              <p className="text-white font-medium">
                Phase 2 — Creator Selection
              </p>

              <p className="mt-1">
                Open applications and select the first creators for the
                second link of the network.
              </p>
            </div>

            <div>
              <p className="text-white font-medium">
                Phase 3 — Open Network
              </p>

              <p className="mt-1">
                Expand token creation access and allow creators to build
                new links under eligible parent tokens.
              </p>
            </div>

            <div>
              <p className="text-white font-medium">
                Phase 4 — Ecosystem
              </p>

              <p className="mt-1">
                Expand the network, creator infrastructure, analytics,
                network visualization and future governance mechanisms.
              </p>
            </div>

          </div>

        </article>


        {/* 12 */}
        <article className="border-t border-white/10 pt-12 mb-16">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            12
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            Risks &amp; Disclaimer
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              CHAINED is an early-stage project. The proposed architecture
              may change substantially during development and there is no
              guarantee that the full protocol will be developed,
              launched or achieve product-market fit.
            </p>

            <p>
              Blockchain assets and protocols involve significant
              technical, market, liquidity, smart contract and regulatory
              risks.
            </p>

            <p>
              The relationships and fee mechanisms described in this
              litepaper represent the intended design direction and may
              change following testing, security review, economic
              analysis and regulatory considerations.
            </p>

            <p>
              Nothing in this litepaper constitutes financial, investment,
              legal or tax advice, and participation in any token or
              protocol involves the possibility of substantial loss.
            </p>

            <p>
              No statement in this document should be interpreted as a
              promise of price appreciation, profit, liquidity or
              successful token performance.
            </p>

          </div>

        </article>


        {/* 13 */}
        <article className="border-t border-white/10 pt-12 mb-20">

          <p className="text-xs tracking-[0.3em] text-gray-600 mb-4">
            13
          </p>

          <h2 className="text-2xl md:text-3xl font-semibold mb-6">
            Closing
          </h2>

          <div className="space-y-5 text-gray-400 leading-8">

            <p>
              CHAINED starts with a simple idea:
            </p>

            <p className="text-2xl md:text-3xl text-white font-semibold leading-relaxed">
              What if launching a token didn&apos;t mean launching alone?
            </p>

            <p>
              CHAIN is the first link.
            </p>

            <p>
              The next links will be created by builders who connect
              their projects to the network. As the network grows,
              economic activity can flow between connected projects
              rather than remaining isolated.
            </p>

            <p>
              The result is intended to be more than a collection of
              individual tokens. It is an ecosystem in which each new
              link can create another point of connection.
            </p>

            <p className="text-white font-medium">
              One chain. Multiple projects. Shared economic relationships.
            </p>

          </div>

        </article>


        {/* FINAL */}
        <div className="border-t border-white/10 pt-16 text-center">

          {/* LARGE FINAL LOGO */}
          <div className="flex justify-center">
            <img
              src="/chained-header.png"
              alt="chained"
              draggable={false}
              className="w-[220px] md:w-[320px] h-auto object-contain select-none"
            />
          </div>

          <p className="mt-5 text-gray-500 tracking-[0.25em] text-sm">
            DON&apos;T LAUNCH ALONE.
          </p>

        </div>


      </section>


      {/* FOOTER */}
      <footer className="border-t border-white/10 px-8 py-8 text-center">

        <p className="text-xs text-gray-600 tracking-[0.25em]">
          CHAINED · LITEPAPER v0.3 · 2026
        </p>

      </footer>

    </main>
  );
}